apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: games-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "games-portfolio"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/games-backend:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: gamesdb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: games-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: games-secrets
                  key: DB_PASSWORD
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: games-secrets
                  key: APP_JWT_SECRET
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql
          emptyDir: {}
      # Attach Cloud SQL Auth Proxy sidecar if using connector
      # Uncomment and configure the sidecar if not using private IP
      # containers:
      #   - name: cloud-sql-proxy
      #     image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
      #     args:
      #       - "--port=5432"
      #       - "PROJECT:REGION:INSTANCE"
      #     securityContext:
      #       runAsNonRoot: true
      #     resources:
      #       limits:
      #         cpu: "0.5"
      #         memory: 256Mi
